AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  VpcName:
    Type: String
    Default: "mgmt-vpc"
  VpcCidrBlock:
    Type: String
    Default: "10.4.0.0/16"
  SubnetName:
    Type: String
    Default: "subnet"
  SubnetCidr:
    Type: String
    Default: "10.4.1.0/24"
  AvailabilityZone:
    Type: String
    Default: "a"
  PanoramaName:
    Type: String
    Default: "panorama"
  PanoramaPrivateIP:
    Type: String
    Default: "10.4.1.100"
  PanoramaInstanceType:
    Type: String
    Default: "m5.2xlarge"
  PanoramaAmi:
    Type: String
    Default: "ami-0a926ff0116b451c8"
  SshKeyName:
    Type: String
    # Add any default value you may have for ssh-key-name in your Terraform variables
  PrefixNameTag:
    Type: String
    # Add any default value you may have for prefix-name-tag in your Terraform variables

Resources:
  ManagementVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidrBlock
      InstanceTenancy: default
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref VpcName

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Ref VpcName

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref ManagementVpc
      InternetGatewayId: !Ref InternetGateway

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref ManagementVpc
      Tags:
        - Key: Name
          Value: "rt"

  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref ManagementVpc
      CidrBlock: !Ref SubnetCidr
      AvailabilityZone: !Ref AvailabilityZone
      Tags:
        - Key: Name
          Value: !Ref SubnetName

  Route:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "panorama-sg"
      VpcId: !Ref ManagementVpc
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 443
          ToPort: 443
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 3978
          ToPort: 3978
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: "-1"

  NetworkInterface:
    Type: AWS::EC2::NetworkInterface
    Properties:
      SubnetId: !Ref Subnet
      PrivateIpAddress: !Ref PanoramaPrivateIP
      SecurityGroups:
        - !GetAtt SecurityGroup.GroupId
      Tags:
        - Key: Name
          Value: !Sub "${PrefixNameTag}${PanoramaName}-primary-interface"

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref PanoramaAmi
      InstanceType: !Ref PanoramaInstanceType
      KeyName: !Ref SshKeyName
      NetworkInterfaces:
        - NetworkInterfaceId: !Ref NetworkInterface
          DeviceIndex: 0
      Tags:
        - Key: Name
          Value: !Sub "${PrefixNameTag}${PanoramaName}"

  ElasticIp:
    Type: AWS::EC2::EIP

  ElasticIpAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt ElasticIp.AllocationId
      NetworkInterfaceId: !Ref NetworkInterface

Outputs:
  PANORAMA_IP_ADDRESS:
    Value: !GetAtt ElasticIp.PublicIp
